### PR TITLE
Include Presto specific SQL translations from the RPresto package

### PR DESCRIPTION
**Pull request by OssiLehtinen**
Using tidyverse type of operations to mutate queries can lead to errors, as incompatible variable types are used.

As an example, doing 

`tbl(con, "table_in_athena") %>% mutate(new_col = as.character(old_col))`

fails, as the generated sql has the statement

`cast(new_cal as text)`,

and Athena doesn't have 'text' as a variable type.

These issues are tackled in the RPresto package (https://github.com/prestodb/RPresto) with the Presto specific SQL translations, which are included in this pull request.

A disclaimer: I am not at all familiar how the licence part works in this kind of situation. I left the licence statements in the new source files in place, which point to the BSD licence at the source project.

### CODE REVIEW

**Comment by DyfanJones** [comment]
Hi @OssiLehtinen these changes look really promising. I will raise an issue ticket with RPresto to see if there is any licensing issue. If not i am happy to pull these changes. The only thing I would change is maybe the documentation so we don't use RPresto's documentation.

**Comment by DyfanJones** [comment]
raise a ticket around licensing with RPresto https://github.com/prestodb/RPresto/issues/117

**Comment by DyfanJones** [comment]
@OssiLehtinen are you able to change the documentation to reference AWS Athena instead of Facebook and presto. I am thinking of something that references: https://docs.aws.amazon.com/athena/latest/ug/data-types.html

Let me know what you think

**Comment by OssiLehtinen** [comment]
I can try my hand on it. Haven't gotten around to documenting any R-packages earlier so be prepared to point out some silly mistakes. The basic process would be to add the roxygen-headers to the R-files, right?

**Comment by DyfanJones** [comment]
@OssiLehtinen i am going to make a push to your master branch with some changes. I believe these changes should help to remove the potential licensing issue :)

**Comment by DyfanJones** [comment]
@OssiLehtinen can you please review the changes and let me know if you approve.

I have ran local cran checks plus the unit tests. 
0 errors ✔ | 0 warnings ✔ | 0 notes ✔

However i think i might need to create some extra unit tests :)

**Comment by OssiLehtinen** [comment]
I'm 'away from keyboard' for the weekend, but will take a look the first thing I get back.

**Comment by DyfanJones** [comment]
Added unit test for `dplyr::translate_sql_env`: 
* OK:       53
* Failed:   0
* Warnings: 0
* Skipped:  0

**Comment by OssiLehtinen** [comment]
@DyfanJones, the changes look good to me!

**Comment by DyfanJones** [comment]
@OssiLehtinen  I have now merged this pull request. I will have to apply these changes on the other Athena package `noctua` once I have done that I will push the changes to the cran. In the mean time you can use `remotes::install_github("dyfanjones/RAthena")`  to pick up the changes.

**Pull request merged**
