### PR TITLE
Add an S3 method for special handling of dates and iso-formatted date strings in dbplyr

### PR DESCRIPTION
**Pull request by OssiLehtinen**
Athena doesn't automatically convert strings to dates when doing comparisons, so for example 'where' conditions need to have date literals. That is, (assuming col1 is a date column), one needs

´ select * from table where col1 = DATE '2020-01-01'

Using a date variable in dplyr in a filter condition does not work, as the date is converted to a string and used as is, resulting in sql such as 

´ select * from table where col1 =  '2020-01-01'

This pull request implements an S3 method, which tries casting the resulting string (or a string vector) to date and if successful adds the 'DATE' prefix.

With this addition, code such as:

```r 
test_date <- Sys.Date()
tbl(con, "table") %>% filter(date_column == test_date)
```
works.

Ideally, we would have date-specific escape methods in dbplyr, but the generics are not there (yet). Those wouldn't help with isodate strings, however.

The draw back of the solution is, that if one does NOT want an iso date string to be converted to a literal, one needs to explicitly cast it to a string, e.g.:
```r
test_date <- Sys.Date()
tbl(con, "table") %>% filter(chr_column == as.character(test_date))
```

### CODE REVIEW

**Comment by DyfanJones** [comment]
Thanks for the pull request. Looks really promising, have you managed to run the unit tests?

**Comment by OssiLehtinen** [comment]
I don't have the test environ configured completely, devtools::test() doesn't test too much, but I ran manually the test related to sql_translate_env.R and those didn't report any problems.

**Comment by DyfanJones** [comment]
ok no worries, i will run the unit tests. does `cast( date'2019-01-01' as date)` work in AWS Athena?

**Comment by OssiLehtinen** [comment]
Yes, `cast( date'2019-01-01' as date)` works.

**Comment by DyfanJones** [comment]
# Unit Test Results:
----------
* OK:       66
* Failed:   0
* Warnings: 0
* Skipped:  0

**Comment by DyfanJones** [comment]
My apologies I didn't notice that `sql_escape_string.AthenaConnection` wasn't exported by `roxygen2`. I will raise a pull request to fix this.

*Note:*  Namespace is created by `roxygen2`, please reference to https://roxygen2.r-lib.org/ when adding new s3 methods. When it comes to adding new s3 methods to packages out side of `Rathena` i.e. `dbplyr`, please register s3 method in `zzz.R` file.

**Comment by OssiLehtinen** [comment]
Ah, sorry, still learning these things. Thanks for the tips!

**Pull request merged**
