### PR TITLE
Fix formatting errors with timestamp on write and read

### PR DESCRIPTION
**Pull request by OssiLehtinen**
The following data.table causes two fold problems when written into and read from athena:
```r
natable <- data.frame(
    a = c(Sys.time(), as.POSIXct("2019-12-31 00:00:00"), NA, as.POSIXct("2019-12-31 23:59:59.999999")), 
    b = c(1, 2, 3, NaN),
    c = c("g", NA, "h", "i")
  )

a_t <- copy_to(con, natable, "test")
a_t
```
First, data.table::fwrite formats the timestamps as iso8601, which does not work with Athena's/Presto's timestamp column type, and empty rows are returned.

The commit to table.R addresses this in a 'hacky' way, by forcing the formatting of the timstamp-columns to something Athena understands and writing them as character-fields. Since this is done after the column definitions are generated, the columns appear as timestamps in Athena.
NB! I do not have Arrow running, so I have no idea what happens when writing as parquet.

Second, empty entries are returned as "" from Athena when reading, and parsing as POSIXct fails with these. Consequently timestamp cols are reverted to strings. 

The commit to result.R addresses this issue, but telling data.table::fread to treat "" as NA.

### CODE REVIEW

**Comment by DyfanJones** [comment]
Current issue with this solution is that it writes the Athena DDL as string. Will problem solve to see if this can be avoided

**Comment by OssiLehtinen** [comment]
The idea is, that the csv has string as input, but the DDL still has timestamp in the columndefinition, so the resulting Athena table actually show timestamp datatypes.  This is because the formatting is done after the field.types are generated.

**Comment by DyfanJones** [comment]
added POXISct format in data transfer unit test

**Comment by OssiLehtinen** [comment]
Works perfectly in my tests now!

**Comment by OssiLehtinen** [comment]
Ah I didn't notice you had done quite a few changes after pushing to my master. Let me know when it's ready for testing.

**Comment by DyfanJones** [comment]
@OssiLehtinen just ran the tests now and it seems all good. Working your end? here are my results:
OK:       53
Failed:   0
Warnings: 0
Skipped:  0

**Comment by OssiLehtinen** [comment]
All is good here as well!

**Comment by DyfanJones** [comment]
@OssiLehtinen i will make these changes to `noctua` and then get the packages ready for cran release.

**Pull request merged**
